name: pokedex
description: Flutter Pokedex.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter_modular: ^3.3.1
  flutter_staggered_animations: ^1.0.0
  rx_notifier: ^1.1.0
  shared_preferences: ^2.0.6
  sliding_sheet: ^0.5.0

  # v2.0.0
  cupertino_icons: 1.0.2
  dio: 4.0.0
  flutter:
    sdk: flutter
  flutter_flavor: 3.0.3
  flutter_launcher_icons: 0.9.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 5.0.2
  fpdart: 0.0.9
  get_it: 7.2.0
  google_fonts: 2.1.0
  json_annotation: 4.4.0
  responsive_framework: 0.1.5

dev_dependencies:
  build_runner: 2.1.5
  flutter_test:
    sdk: flutter
  json_serializable: 6.1.1
  mocktail: 0.1.4

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/assets/images/icon.png"
  image_path_android: "lib/assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

vars:
  enable_web: flutter config --enable-web
  no_enable_web: flutter config --no-enable-web
  clean: flutter clean
  get: flutter pub get
  pkg: flutter packages get
  runner: flutter pub run build_runner
  icon: flutter pub run flutter_launcher_icons:main
  appbundle: flutter build appbundle -t
  apk: flutter build apk -t
  ios: flutter build ios -t
  dev: lib/main.dart

scripts:
  enable_web: $enable_web
  no_enable_web: $no_enable_web
  clean: $clean & $get & $pkg
  watch: $runner watch --delete-conflicting-outputs
  build_runner: $runner build --delete-conflicting-outputs
  build_icon: $icon
  build_android_dev: $appbundle $dev
  build_apk_dev: $apk $dev
  build_ios_dev: $ios $dev
