name: pokedex
description: Flutter Pokedex.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^3.3.1
  flutter_staggered_animations: ^1.0.0
  fpdart: ^0.0.9
  google_fonts: ^2.1.0
  rx_notifier: ^1.1.0
  shared_preferences: ^2.0.6
  sliding_sheet: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.4

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/assets/images/icon.png"
  image_path_android: "lib/assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/

vars:
  clean: flutter clean
  get: flutter pub get
  pkg: flutter packages get
  runner: flutter pub run build_runner
  icon: flutter pub run flutter_launcher_icons:main
  appbundle: flutter build appbundle -t
  apk: flutter build apk -t
  ios: flutter build ios -t
  dev: lib/main.dart

scripts:
  clean: $clean & $get & $pkg
  watch: $runner watch --delete-conflicting-outputs
  build_runner: $runner build --delete-conflicting-outputs
  build_icon: $icon
  build_android_dev: $appbundle $dev
  build_apk_dev: $apk $dev
  build_ios_dev: $ios $dev
